# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(686, 435)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.precisionTextEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.precisionTextEdit.setGeometry(QtCore.QRect(20, 100, 131, 21))
        self.precisionTextEdit.setObjectName("precisionTextEdit")
        self.epochsTextEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.epochsTextEdit.setGeometry(QtCore.QRect(340, 40, 131, 21))
        self.epochsTextEdit.setObjectName("epochsTextEdit")
        self.populationSizeTextEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.populationSizeTextEdit.setGeometry(QtCore.QRect(180, 100, 131, 21))
        self.populationSizeTextEdit.setObjectName("populationSizeTextEdit")
        self.crossProbabilityTextEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.crossProbabilityTextEdit.setGeometry(QtCore.QRect(520, 100, 111, 21))
        self.crossProbabilityTextEdit.setObjectName("crossProbabilityTextEdit")
        self.inversionProbabilityTextEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.inversionProbabilityTextEdit.setGeometry(QtCore.QRect(20, 160, 131, 21))
        self.inversionProbabilityTextEdit.setObjectName("inversionProbabilityTextEdit")
        self.eliteStrategyTextEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.eliteStrategyTextEdit.setGeometry(QtCore.QRect(180, 160, 131, 21))
        self.eliteStrategyTextEdit.setObjectName("eliteStrategyTextEdit")
        self.optimizationMethodGroupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.optimizationMethodGroupBox.setGeometry(QtCore.QRect(340, 260, 291, 81))
        self.optimizationMethodGroupBox.setObjectName("optimizationMethodGroupBox")
        self.minimumRadioButton = QtWidgets.QRadioButton(parent=self.optimizationMethodGroupBox)
        self.minimumRadioButton.setGeometry(QtCore.QRect(10, 20, 101, 20))
        self.minimumRadioButton.setChecked(True)
        self.minimumRadioButton.setObjectName("minimumRadioButton")
        self.maximumRadioButton = QtWidgets.QRadioButton(parent=self.optimizationMethodGroupBox)
        self.maximumRadioButton.setGeometry(QtCore.QRect(10, 40, 101, 20))
        self.maximumRadioButton.setObjectName("maximumRadioButton")
        self.crossMethodComboBox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.crossMethodComboBox.setGeometry(QtCore.QRect(340, 100, 161, 22))
        self.crossMethodComboBox.setObjectName("crossMethodComboBox")
        self.crossMethodComboBox.addItem("")
        self.crossMethodComboBox.addItem("")
        self.crossMethodComboBox.addItem("")
        self.crossMethodComboBox.addItem("")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 80, 71, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(180, 80, 81, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(340, 80, 81, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(520, 80, 91, 16))
        self.label_6.setObjectName("label_6")
        self.label_9 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(340, 20, 49, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(500, 20, 131, 16))
        self.label_10.setObjectName("label_10")
        self.paramNumbersTextEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.paramNumbersTextEdit.setGeometry(QtCore.QRect(500, 40, 131, 21))
        self.paramNumbersTextEdit.setObjectName("paramNumbersTextEdit")
        self.label_11 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(180, 140, 151, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(20, 140, 121, 20))
        self.label_12.setObjectName("label_12")
        self.calculateFunctionComboBox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.calculateFunctionComboBox.setGeometry(QtCore.QRect(340, 220, 291, 22))
        self.calculateFunctionComboBox.setObjectName("calculateFunctionComboBox")
        self.calculateFunctionComboBox.addItem("")
        self.calculateFunctionComboBox.addItem("")
        self.label_13 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(340, 200, 131, 16))
        self.label_13.setObjectName("label_13")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 0, 311, 71))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(10, 20, 111, 16))
        self.label.setObjectName("label")
        self.rangeBeginningTextEdit = QtWidgets.QTextEdit(parent=self.groupBox_2)
        self.rangeBeginningTextEdit.setGeometry(QtCore.QRect(10, 40, 131, 21))
        self.rangeBeginningTextEdit.setObjectName("rangeBeginningTextEdit")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(170, 20, 61, 16))
        self.label_2.setObjectName("label_2")
        self.rangeEndTextEdit = QtWidgets.QTextEdit(parent=self.groupBox_2)
        self.rangeEndTextEdit.setGeometry(QtCore.QRect(170, 40, 131, 21))
        self.rangeEndTextEdit.setObjectName("rangeEndTextEdit")
        self.mutationProbabilityTextEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.mutationProbabilityTextEdit.setGeometry(QtCore.QRect(520, 160, 111, 21))
        self.mutationProbabilityTextEdit.setObjectName("mutationProbabilityTextEdit")
        self.label_8 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(520, 140, 111, 16))
        self.label_8.setObjectName("label_8")
        self.mutationMethodComboBox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.mutationMethodComboBox.setGeometry(QtCore.QRect(340, 160, 161, 22))
        self.mutationMethodComboBox.setObjectName("mutationMethodComboBox")
        self.mutationMethodComboBox.addItem("")
        self.mutationMethodComboBox.addItem("")
        self.mutationMethodComboBox.addItem("")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(340, 140, 101, 16))
        self.label_7.setObjectName("label_7")
        self.label_14 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(20, 200, 101, 16))
        self.label_14.setObjectName("label_14")
        self.selectionMethodComboBox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.selectionMethodComboBox.setGeometry(QtCore.QRect(20, 220, 291, 22))
        self.selectionMethodComboBox.setObjectName("selectionMethodComboBox")
        self.selectionMethodComboBox.addItem("")
        self.selectionMethodComboBox.addItem("")
        self.selectionMethodComboBox.addItem("")
        self.bestToSelectTextEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.bestToSelectTextEdit.setGeometry(QtCore.QRect(20, 280, 131, 21))
        self.bestToSelectTextEdit.setObjectName("bestToSelectTextEdit")
        self.tournamentSizeTextEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.tournamentSizeTextEdit.setGeometry(QtCore.QRect(180, 280, 131, 21))
        self.tournamentSizeTextEdit.setObjectName("tournamentSizeTextEdit")
        self.calculateButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.calculateButton.setGeometry(QtCore.QRect(20, 320, 291, 24))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Button, brush)
        self.calculateButton.setPalette(palette)
        self.calculateButton.setAutoFillBackground(False)
        self.calculateButton.setObjectName("calculateButton")
        self.label_15 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(20, 260, 171, 16))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(180, 260, 101, 16))
        self.label_16.setObjectName("label_16")
        self.warningLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.warningLabel.setGeometry(QtCore.QRect(20, 360, 611, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Text, brush)
        self.warningLabel.setPalette(palette)
        self.warningLabel.setText("")
        self.warningLabel.setObjectName("warningLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 686, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.precisionTextEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0.001</p></body></html>"))
        self.epochsTextEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">20</p></body></html>"))
        self.populationSizeTextEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">200</p></body></html>"))
        self.crossProbabilityTextEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0.5</p></body></html>"))
        self.inversionProbabilityTextEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0.76</p></body></html>"))
        self.eliteStrategyTextEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0.44</p></body></html>"))
        self.optimizationMethodGroupBox.setTitle(_translate("MainWindow", "Search optimum"))
        self.minimumRadioButton.setText(_translate("MainWindow", "Minimum"))
        self.maximumRadioButton.setText(_translate("MainWindow", "Maximum"))
        self.crossMethodComboBox.setItemText(0, _translate("MainWindow", "One Point"))
        self.crossMethodComboBox.setItemText(1, _translate("MainWindow", "Two Points"))
        self.crossMethodComboBox.setItemText(2, _translate("MainWindow", "Homogenius"))
        self.crossMethodComboBox.setItemText(3, _translate("MainWindow", "Granular"))
        self.label_3.setText(_translate("MainWindow", "Precision"))
        self.label_4.setText(_translate("MainWindow", "Population size"))
        self.label_5.setText(_translate("MainWindow", "Cross method"))
        self.label_6.setText(_translate("MainWindow", "Cross probability"))
        self.label_9.setText(_translate("MainWindow", "Epochs"))
        self.label_10.setText(_translate("MainWindow", "Number of parameters"))
        self.paramNumbersTextEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">5</p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "Elite strategy %"))
        self.label_12.setText(_translate("MainWindow", "Inversion probability"))
        self.calculateFunctionComboBox.setItemText(0, _translate("MainWindow", "Michalewicz"))
        self.calculateFunctionComboBox.setItemText(1, _translate("MainWindow", "Shifted and Rotated HappyCat Function"))
        self.label_13.setText(_translate("MainWindow", "Function to find optimum"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Range"))
        self.label.setText(_translate("MainWindow", "Begin"))
        self.rangeBeginningTextEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1</p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "End"))
        self.rangeEndTextEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">100</p></body></html>"))
        self.mutationProbabilityTextEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0.55</p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "Mutation probability"))
        self.mutationMethodComboBox.setItemText(0, _translate("MainWindow", "Edge"))
        self.mutationMethodComboBox.setItemText(1, _translate("MainWindow", "One Point"))
        self.mutationMethodComboBox.setItemText(2, _translate("MainWindow", "Two Points"))
        self.label_7.setText(_translate("MainWindow", "Mutation method"))
        self.label_14.setText(_translate("MainWindow", "Selection method"))
        self.selectionMethodComboBox.setItemText(0, _translate("MainWindow", "Best Selection"))
        self.selectionMethodComboBox.setItemText(1, _translate("MainWindow", "Roulette Selection"))
        self.selectionMethodComboBox.setItemText(2, _translate("MainWindow", "Tournament Selection"))
        self.bestToSelectTextEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0.33</p></body></html>"))
        self.tournamentSizeTextEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">40</p></body></html>"))
        self.calculateButton.setText(_translate("MainWindow", "Calculate"))
        self.label_15.setText(_translate("MainWindow", "% of best to select"))
        self.label_16.setText(_translate("MainWindow", "Tournament size"))
        self.precisionTextEdit.setText("2")




