# Form implementation generated from reading ui file 'plots.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

class Ui_PlotsWindow(object):
    def setupUi(self, PlotsWindow):
        PlotsWindow.setObjectName("PlotsWindow")
        PlotsWindow.resize(724, 433)
        self.centralwidget = QtWidgets.QWidget(parent=PlotsWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(10, 30, 551, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(570, 90, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.timeValue = QtWidgets.QLabel(parent=self.centralwidget)
        self.timeValue.setGeometry(QtCore.QRect(570, 110, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.timeValue.setFont(font)
        self.timeValue.setObjectName("timeValue")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(570, 220, 49, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(570, 150, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.fitnessResultValue = QtWidgets.QLabel(parent=self.centralwidget)
        self.fitnessResultValue.setGeometry(QtCore.QRect(570, 170, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fitnessResultValue.setFont(font)
        self.fitnessResultValue.setObjectName("fitnessResultValue")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(570, 240, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 10, 91, 16))
        self.label_7.setObjectName("label_7")
        self.plotArea = QtWidgets.QWidget(parent=self.centralwidget)
        self.plotArea.setGeometry(QtCore.QRect(10, 60, 551, 311))
        self.plotArea.setObjectName("plotArea")
        PlotsWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=PlotsWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 724, 22))
        self.menubar.setObjectName("menubar")
        PlotsWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=PlotsWindow)
        self.statusbar.setObjectName("statusbar")
        PlotsWindow.setStatusBar(self.statusbar)

        self.retranslateUi(PlotsWindow)
        QtCore.QMetaObject.connectSlotsByName(PlotsWindow)

    def retranslateUi(self, PlotsWindow):
        _translate = QtCore.QCoreApplication.translate
        PlotsWindow.setWindowTitle(_translate("PlotsWindow", "Plots"))
        self.comboBox.setItemText(0, _translate("PlotsWindow", "Average Fitness Value Over Iterations"))
        self.comboBox.setItemText(1, _translate("PlotsWindow", "Minimum Fitness Value Over Iterations"))
        self.comboBox.setItemText(2, _translate("PlotsWindow", "Standard Deviation of Fitness Value Over Iterations"))
        self.label.setText(_translate("PlotsWindow", "Calculation Time:"))
        self.timeValue.setText(_translate("PlotsWindow", "TimeValue"))
        self.label_3.setText(_translate("PlotsWindow", "Results:"))
        self.label_4.setText(_translate("PlotsWindow", "Fitness Result"))
        self.fitnessResultValue.setText(_translate("PlotsWindow", "FitnessResultValue"))
        self.label_6.setText(_translate("PlotsWindow", "ResultsValue"))
        self.label_7.setText(_translate("PlotsWindow", "Choose Plot:"))



